import fs from "node:fs";
import { DEFAULT_PARAMS, aeroCoeffs } from "../src/vehicle";
import { centerlineFromLap } from "../src/track";

// Validation: quasi-steady-state (QSS) lap-time simulation over the fitted
// Monza racing line, using the same vehicle parameters the game drives with.
// Classic three-pass method: corner-speed limit from the friction circle
// (with downforce), then forward accel / backward braking passes.
// Compared against the real lap the line was fitted from.
// Run: npm run validate

const RHO = 1.2;
const G = 9.81;

const sess = JSON.parse(fs.readFileSync("public/sessions/monza-2024.json", "utf8"));
const curve = centerlineFromLap(sess.x, sess.z);
const p = DEFAULT_PARAMS;
const aero = aeroCoeffs(p, false);
const mu = p.mu; // medium compound at peak temperature ≈ grip factor 1.0

const N = 4000;
const pts = Array.from({ length: N }, (_, i) => curve.getPointAt(i / N));
const ds: number[] = [];
const kappa: number[] = [];
for (let i = 0; i < N; i++) {
  const a = pts[i];
  const b = pts[(i + 1) % N];
  const c = pts[(i + 2) % N];
  ds.push(Math.hypot(b.x - a.x, b.z - a.z));
  // Curvature via circumradius of three consecutive points
  const ab = Math.hypot(b.x - a.x, b.z - a.z);
  const bc = Math.hypot(c.x - b.x, c.z - b.z);
  const ca = Math.hypot(a.x - c.x, a.z - c.z);
  const area2 = Math.abs((b.x - a.x) * (c.z - a.z) - (b.z - a.z) * (c.x - a.x));
  kappa.push(ab * bc * ca > 1e-9 ? (2 * area2) / (ab * bc * ca) : 0);
}

// 1. Corner-speed limit: m v² κ = μ (m g + ½ρ ClA v²)  →  solve for v²
const vLim = kappa.map((k) => {
  if (k < 1e-5) return 110;
  const denom = p.mass * k - mu * 0.5 * RHO * aero.clA;
  if (denom <= 0) return 110; // aero-limited: flat at any speed
  return Math.min(110, Math.sqrt((mu * p.mass * G) / denom));
});

// 2/3. Forward + backward passes with friction-circle long/lat coupling
function gripLongAccel(v: number, k: number): number {
  const load = p.mass * G + 0.5 * RHO * aero.clA * v * v;
  const aTot = (mu * load) / p.mass;
  const aLat = v * v * k;
  return aTot > aLat ? Math.sqrt(aTot * aTot - aLat * aLat) : 0;
}
const dragAccel = (v: number) => (0.5 * RHO * aero.cdA * v * v + 0.015 * p.mass * G) / p.mass;

const v = vLim.slice();
for (let pass = 0; pass < 3; pass++) {
  // Forward: traction/power-limited acceleration
  for (let i = 0; i < 2 * N; i++) {
    const j = i % N;
    const nx = (j + 1) % N;
    const aDrive = Math.min(gripLongAccel(v[j], kappa[j]), p.powerMax / (p.mass * Math.max(v[j], 5)));
    const a = aDrive - dragAccel(v[j]);
    v[nx] = Math.min(vLim[nx], Math.sqrt(Math.max(1, v[j] * v[j] + 2 * a * ds[j])));
  }
  // Backward: brake-force + grip-limited deceleration (drag helps)
  for (let i = 2 * N; i > 0; i--) {
    const j = i % N;
    const pv = (j - 1 + N) % N;
    const aBrake = Math.min(gripLongAccel(v[j], kappa[j]), p.brakeForceMax / p.mass) + dragAccel(v[j]);
    v[pv] = Math.min(v[pv], Math.sqrt(v[j] * v[j] + 2 * aBrake * ds[pv]));
  }
}

let lapTime = 0;
for (let i = 0; i < N; i++) lapTime += ds[i] / ((v[i] + v[(i + 1) % N]) / 2);
const trackLen = ds.reduce((a, b) => a + b, 0);

const realLap = sess.meta.lap_time_s as number;
const realVmax = Math.max(...(sess.speed as number[]));
const realVmin = Math.min(...(sess.speed as number[]));
const simVmax = Math.max(...v);
const simVmin = Math.min(...v);
const err = ((lapTime - realLap) / realLap) * 100;

const report = `# Validation — QSS lap simulation vs OpenF1 telemetry

**Case:** ${sess.meta.circuit} ${sess.meta.year}, car ${sess.meta.driver_number}, race lap ${sess.meta.lap_number} (fastest).
**Method:** quasi-steady-state lap-time simulation on the racing line fitted from the
telemetry itself, using the game's vehicle parameters (\`DEFAULT_PARAMS\`) — friction-circle
corner limits with downforce, power-limited forward pass, brake-limited backward pass.
DRS and ERS deployment are not modeled in the QSS pass (both add pace on straights).

| Quantity | Simulated | Real (OpenF1) | Error |
|---|---|---|---|
| Lap time | ${lapTime.toFixed(2)} s | ${realLap.toFixed(3)} s | ${err >= 0 ? "+" : ""}${err.toFixed(1)}% |
| Top speed | ${(simVmax * 3.6).toFixed(0)} km/h | ${(realVmax * 3.6).toFixed(0)} km/h | ${(((simVmax - realVmax) / realVmax) * 100).toFixed(1)}% |
| Slowest corner | ${(simVmin * 3.6).toFixed(0)} km/h | ${(realVmin * 3.6).toFixed(0)} km/h | ${(((simVmin - realVmin) / realVmin) * 100).toFixed(1)}% |
| Track length (fitted) | ${trackLen.toFixed(0)} m | 5793 m (official) | ${(((trackLen - 5793) / 5793) * 100).toFixed(1)}% |

Generated by \`npm run validate\` (test/lap-sim.ts) on the committed session JSON.
`;
fs.writeFileSync("docs/validation.md", report);
console.log(report);

// Hard gates: the model must stay in the physical ballpark of the real lap
if (Math.abs(err) > 8) throw new Error(`lap time error ${err.toFixed(1)}% exceeds 8% gate`);
if (Math.abs(simVmax - realVmax) / realVmax > 0.08) throw new Error("top speed off by more than 8%");
console.log("validation gates passed");
